### ISSUE TITLE
Second Home not in list.

### ISSUE THREAD

**Issue by NoobTaco** [mmonkey/Destinations#2]
**Expected Results** Adding a second home to the system should result in it showing up in the /showhomes command.

**Actual Results** Only the first home is listed. However both are saved and you are able to /home back to each of them.

**Steps**
- Start with fresh server install.
- Create the first home.
- Type /showhomes (Notice it is not listed)
- Create a second home.
  *Type /showhomes

![2015-05-11_17 06 24](https://cloud.githubusercontent.com/assets/1172935/7576131/458f1050-f800-11e4-9040-0adf80f20032.png)

**Comment by mmonkey** [comment]
The changes are there, I just need to recompile the plugin. It slipped my mind last week! I'll get it done this evening and close the issue.

**Comment by mmonkey** [comment]
Fixed in [v0.0.21](../releases/tag/0.0.21)
