### ISSUE TITLE
doesn't build with sponge api 3.0.0

### ISSUE THREAD

**Issue by tdugger** [mmonkey/Destinations#5]
wondering...
1) will @mmonkey will be updating the code to work with 3.0.0 API (it is a fair chunk of work so don't want multiple people doing it).
2) or is this plugin now defunct and replaced by a better one?

**Comment by mmonkey** [comment]
@tdugger 
1) I will be updating the plugin, however it may be a while until I have the time to do it. I don't think it will be too long by any means.
2) Destinations is not defunct, and I am always looking for ways to improve my plugins. The eventual goal is to have the best plugin for teleportation, so hopefully "a better one" doesn't exist.

I will keep this issue open until I get the plugin updated.

**Comment by tdugger** [comment]
@mmonkey 
ok.. here's what I have learned so far..

1) Player moved.
-import org.spongepowered.api.entity.player.Player;
+import org.spongepowered.api.entity.living.player.Player;

2) Texts changed.
+import org.spongepowered.api.text.Text;
-import org.spongepowered.api.text.TextBuilder;  //use Text.Builder
-import org.spongepowered.api.text.Texts;

3) util command classes moved to their own package
-import org.spongepowered.api.util.command.CommandException;
-import org.spongepowered.api.util.command.CommandResult;
-import org.spongepowered.api.util.command.CommandSource;
-import org.spongepowered.api.util.command.args.CommandContext;
-import org.spongepowered.api.util.command.spec.CommandExecutor;
+import org.spongepowered.api.command.CommandException;
+import org.spongepowered.api.command.CommandResult;
+import org.spongepowered.api.command.CommandSource;
+import org.spongepowered.api.command.args.CommandContext;
+import org.spongepowered.api.command.spec.CommandExecutor;

4) have to build with Java 8

**Comment by tdugger** [comment]
5) AbstractEvent moved.
-import org.spongepowered.api.event.AbstractEvent;
+import org.spongepowered.api.event.impl.AbstractEvent;

6) SchedulerService changed.
-import org.spongepowered.api.service.scheduler.SchedulerService;
+import org.spongepowered.api.scheduler.Scheduler;

**Comment by mmonkey** [comment]
@tdugger Thanks for all of the great info, I have finally updated for Sponge API v3.0.0. Also see [Commando](https://github.com/mmonkey/Commando/releases/tag/v0.0.2-3.0.0) for updates.
